---

name: PR


on:
  pull_request: {}
  workflow_call:


jobs:
  conventional:
    name: Conventional PR Title
    runs-on: ubuntu-latest
    steps:


      - name: check-for-cc
        # if: ${{ github.event.pull_request }}
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-title-regex: "^(.+)(?:(([^)s]+)))?: (.+)"
          pr-body-regex: "(.*)"
