---

name: 'Process Coverage Artifact'

on:
  workflow_run:
    workflows:
      - 'Unit Test'
    types:
      - completed


permissions:
  contents: read
  actions: read
  checks: write


jobs:
  report:
    runs-on: ubuntu-latest
    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: ['3.12']
    name: Coverage
    steps:
    
      - name: Run Tests
        run: |
          ls -l;

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-3.12
          # path: coverage.xml
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: ls
        if: success() || failure()
        run: |
          ls -l;

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 85'


      # - name: Add Coverage PR Comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   if: github.event_name == 'pull_request'
      #   with:
      #     recreate: true
      #     path: code-coverage-results.md


      - name: ls
        if: success() || failure()
        run: |
          ls -l;

      # - name: Adding markdown
      #   run: |
      #     cat $(ls *.md | tail -1) >> $GITHUB_STEP_SUMMARY

      - name: create status check/comment for code coverage results
        id: jest_coverage_check
        uses: im-open/process-code-coverage-summary@v2.3.0
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ github.token }}
          summary-file: code-coverage-results.md
          create-pr-comment: true
          update-comment-if-one-exists: true
          update-comment-key: "${{ env.GITHUB-JOB }}_${{ env.GITHUB-ACTION }}"

      - name: Upload Coverage Summary
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: code-coverage-results-3.12
          path: code-coverage-results.md
