---

name: Pull Requests


on:
  workflow_call:


jobs:

  conventional-pr-title:
    name: Conventional PR Title
    runs-on: ubuntu-latest
    steps:


      - name: Conventional Commit PR Title
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-title-regex: "^(.+)(?:(([^)s]+)))?: (.+)"
          pr-body-regex: "(.*)"


  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:

      - name: Check Commits
        uses: taskmedia/action-conventional-commits@v1.1.17
        with:
          token: ${{ github.token }}
          skip_merge: true
          skip_revert: true
          types: "build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test"

