---

name: Pull Requests


on:
  workflow_call:


jobs:

  conventional-pr-title:
    name: Conventional PR Title
    runs-on: ubuntu-latest
    steps:


      - name: Conventional Commit PR Title
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-title-regex: "^(.+)(?:(([^)s]+)))?: (.+)"
          pr-body-regex: "(.*)"


  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:

      - name: Check Commits
        uses: taskmedia/action-conventional-commits@v1.1.17
        with:
          token: ${{ github.token }}
          skip_merge: true
          skip_revert: true
          types: "build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test"


  pr_dependencies:
    runs-on: ubuntu-latest
    name: Dependency Check
    steps:
    - uses: gregsdennis/dependencies-action@4fc2a4879387b43f784920699cb9303dd0524ac4
      with:
        custom-domains: my-custom-domain.io another.domain.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
