name: Release

on:
  workflow_call:



jobs:
  release:
    name: Release
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:


      - name: Create GH Release
        if: ${{ github.ref_type == 'tag' }}
        id: release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            # A title block

            Some release text

            A [link](https://nofusscomputing.com) does render as markdown works.


  release-label:
    if: ${{ github.ref_type == 'tag' }}
    name: Create Release Label
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:

      - run: |
          mkdir -p .github;
          echo "
          labels:
            v${{ github.ref_name }}:
              color: "EEE600"
              description: Version Affected.

          " > .github/labels.yml;

          cat .github/labels.yml;


      - uses: oliversalzburg/action-label-manager@v0.0.9
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
