---

name: 'Process Unit Test Artifact'

on:
  workflow_run:
    workflows:
      - 'Unit Test'
    types:
      - completed


permissions:
  contents: read
  actions: read
  checks: write


jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:

      - name: Test Report
        if: success() || failure()
        uses: dorny/test-reporter@v1
        id: test-report
        with:
          artifact: unit-test-results-${{ matrix.python-version }}
          badge-title: 'Unit Tests [Python ${{ matrix.python-version }}]'
          name: Unit Test Report [Python ${{ matrix.python-version }}]
          path: '*.xml'
          reporter: java-junit


      - name: Create Shields.io Endpoint.json
        if: success() || failure()
        run: |
          echo "
          {
            "schemaVersion": 1,
            "label": "Unit Test",
            "message": "${{ steps.test-report.outputs.passed }} passed | ${{ steps.test-report.outputs.skipped }} skipped",
            "namedLogo": "github",
            "color": "#000"
          }" > endpoint_${{ matrix.python-version }}.json


      - name: Upload Badge Endpoint json
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: unit-test-shield-endpoint-${{ matrix.python-version }}
          path: endpoint_${{ matrix.python-version }}.json
